name: CMake

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        shell: bash
        working-directory: ${{github.workspace}}/
        run: git clone https://github.com/mihail-8480/mh && git clone https://github.com/mihail-8480/mhserv
      - name: Build libmh and install
        working-directory: ${{github.workspace}}/
        shell: bash
        run: cmake mh && cmake --build mh && su -c 'cmake --install mh'
      - name: Build mhserv
        working-directory: ${{github.workspace}}/
        shell: bash
        run: cmake mhserv && cmake --build mhserv
      - name: Run Tests
        working-directory: ${{github.workspace}}/
        shell: bash
        run: mhserv/bin/tests