name: CMake

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build
      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake . && make
      - name: Upload Libraries
        uses: actions/upload-artifact@v2.2.3
        with:
          name: libs-bin
          path: ${{github.workspace}}/build/*.so
          if-no-files-found: ignore
      - name: Upload Executable
        uses: actions/upload-artifact@v2.2.3
        with:
          name: mhserv-bin
          path: ${{github.workspace}}/build/mhserv
          if-no-files-found: ignore
