name: CMake

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        shell: bash
        working-directory: ${{github.workspace}}/
        run: git clone https://github.com/mihail-8480/mh && git clone https://github.com/mihail-8480/mhserv
      - name: Build libmh and install
        working-directory: ${{github.workspace}}/mh
        shell: bash
        run: cmake . -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/ && cmake --build . && cmake --install .
      - name: Build mhserv
        working-directory: ${{github.workspace}}/mhserv
        shell: bash
        run: cmake . && cmake --build .
      - name: Run Tests
        working-directory: ${{github.workspace}}/
        shell: bash
        run: LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{github.workspace}}/lib mhserv/bin/tests